### ISSUE TITLE
prop "text" did not update properly

### ISSUE THREAD

**Issue by shilik** [Remeic/vue-highlighter#11]
Hi, I got a problem of updating the property of "text"
I tried to make the content of "text" change based on the need of users.
But the content of "text" didn't update accordingly when a new value is assigned to it.
any suggestion?

   
![snipaste_2018-05-19_13-09-43](https://user-images.githubusercontent.com/1404868/40265177-f9d2183e-5b65-11e8-92b0-c387d0d01f90.png)
The test code is as the following:
![snipaste_2018-05-19_13-11-52](https://user-images.githubusercontent.com/1404868/40265199-650868c4-5b66-11e8-886e-0eede70c840b.png)

**Comment by Remeic** [comment]
Hi @shilik, i'm figure it out with @astagi but for now seem there is no solution, when a directive is bind to element, element doesn't update correctly

I will continue to look for a solution

**Comment by shilik** [comment]
Hi, @Remeic 
Thank you for the response. Hopefully, this issue will be resolved sooner.

Best regards,

**Comment by shilik** [comment]
Hi, jtommy
Does this mean the problem above is solved?

shilik

**Comment by Remeic** [comment]
@shilik sorry for the delay, in the last week I was submerged in things to do, tomorrow I accept the pr

**Comment by shilik** [comment]
@Remeic 
Thank you very much.

shilik

**Comment by Remeic** [comment]
@shilik Sorry for delay

**Comment by shilik** [comment]
![snipaste_2018-06-01_07-39-55](https://user-images.githubusercontent.com/1404868/40813759-15652826-656f-11e8-9992-d903346d3fec.png)
![snipaste_2018-06-01_07-41-43](https://user-images.githubusercontent.com/1404868/40813802-42c70fb4-656f-11e8-9c21-599312ef3ac2.png)

well, It seems nothing changed even after the patch.
Any suggestion?

**Comment by Remeic** [comment]
@shilik try to update now the node module

**Comment by shilik** [comment]
@Remeic  I noticed the version no. is updated. So I tried to update the plugin again, but nothing changed as a result. Please let know when this issue is fixed. Thank you very much.

**Comment by Remeic** [comment]
@shilik Sorry for delay, can you share your code? because i can't replicate this issue

**Comment by shilik** [comment]
@Remeic 
Thanks for the response and great patch!
It works great on my projects now! 
Credit to you! :)

Shilik
![fast_reading](https://user-images.githubusercontent.com/1404868/41527004-6d563a14-7318-11e8-8188-9d5bb7ca2f42.png)

**Comment by Remeic** [comment]
thank you @shilik! I'm so happy that everything works and that you use the directive in a real project, thank you very much!
