### ISSUE TITLE
[Feature] fuzzy matching

### ISSUE THREAD

**Issue by ctf0** [Remeic/vue-highlighter#13]
atm it respects the lower case / upper case, but with fuzzy search the highlighter could/would match both.

**Comment by Remeic** [comment]
Hi @ctf0 thanks for contributing, yes at the moment respect lower and uppercase, i'm considering to add fuzzy search and i try first implementation in this week or later, thanks again!
For any other suggest don't hesitate to write again!

**Comment by dangilkerson** [comment]
I'd like to work on this.

**Comment by dangilkerson** [comment]
If the regex did a case-insensitive search would that be enough?

**Comment by ctf0** [comment]
mostly yes unless you want to go full fuzzy searching

**Comment by Remeic** [comment]
For satisfy the request of @ctf0 i advise to implement full fuzzy searching

**Comment by dangilkerson** [comment]
Do we want to match things like misspellings? How "fuzzy" do we want to make the search?

**Comment by Remeic** [comment]
@ctf0

**Comment by ctf0** [comment]
- for the main request, i honestly was after the `case-insensitive search`
- but for full fuzzy search, yes it would match `misspellings` too

**Comment by dangilkerson** [comment]
Solving the fuzzy search next

**Comment by ctf0** [comment]
do we still need this ?
