### ISSUE TITLE
[Vue warn]: Failed to resolve directive: highlight

### ISSUE THREAD

**Issue by guiltyvictim** [Remeic/vue-highlighter#25]
Can't seem to get this to work at all, get the titled warning.

vue@2.6.12

**Comment by Remeic** [comment]
Hi, thanks for opening the issue.
How do you import the directive?
Can provide a little snippet of code? Thanks in advance!

**Comment by guiltyvictim** [comment]
Sorry I've gone with another plugin that worked so I don't have the snippet anymore.

I did triple check and copied and pasted your example code, so I'm not sure what had gone wrong. I wonder if it's possibly some changes to Vue.js since the last update to the plugin a year ago that broke it?

**Comment by Remeic** [comment]
Hey @guiltyvictim, yes seems that something is broken...
I think some breaking change in vue changed the way to declare or install vue plugin.

Open this issue to hacktoberfest maybe can be a opportunity for new contrributor to enter in this project!
Really thanks to you for opening this issue, i hope you return to use this directive in future!

**Comment by aaronzshey** [comment]
@Remeic @guiltyvictim I'm basically doing a vue crash course this morning, haha, and I think the directive is miswritten.
https://vuejs.org/v2/guide/custom-directive.html 
I'm also on vue 2.6.12

Edit: It worked - someone built it off of a boilerplate for me - https://codesandbox.io/s/working-vuehighlight-demo-g3hyq?file=/src/main.js

See #29  for more info.

**Comment by Remeic** [comment]
Hey @CarlyRaeJepsenStan, you've done an awesome job!
Really thanks!
